# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: source/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
   - pdf

conda:
  environment: conda/gridTools_export-linux-64-RTD.yml
