name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - jr3cermak
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: how-to-replicate
    attributes:
      label: How to replicate?
      description: Describe how to replicate this bug?
      placeholder: Help us replicate the bug.
      value: "I did this..."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log or error output
      description: Please copy and paste any relevant log or error output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: global-attributes
    attributes:
      label: global attributes
      description: If you are able to create a model grid file, run ncdump -h on the file and provide the global attributes.
      render: shell
